version: '3'
services:
  frontend:
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
  backend:
    image: strapi/strapi
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /data/data.db
    volumes:
      - ./backend/app:/srv/app
      - ./backend/data:/data
